project_name: freeport

release:
  github:
    owner: ajschmidt8
    name: freeport

builds:
  - binary: freeport
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
    main: ./cmd/freeport
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: binary
    replacements:
      amd64: x86_64
      arm64: aarch64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
